número1 = int(input("Digite o primeiro número"))
número2 = int(input("Digite o segundo número"))
print(f"A soma de {número1} e {número2} é igual a {número1+número2}.")
print(f"A subtração de {número1} e {número2} é igual a {número1-número2}.")
print(f"A multiplicação de {número1} e {número2} é igual a {número1*número2}.")
print(f"A divisão de {número1} e {número2} é igual a {número1/número2}.")
print(f"A potencia de {número1} e {número2} é igual a {número1**número2}.")
print(f"A divisão inteira de {número1} e {número2} é igual a {número1//número2}.")
print(f"O resto da divisão de {número1} e {número2} é igual a {número1%número2}.")